package logic.playerTypes;

import logic.logicTransfer.GUIConnector;
import logic.playerState.Player;

/**
 * Enum serving as a static factory of the player class
 */
public enum PlayerType {
    HUMAN("Menschlicher Spieler"),
    DEFAULT("Standard Gegner"),
    CAPABLE_OF_MOVING_BOARD("Not supported yet"),
    INVOLVE_NEXT_BANK("Not supported yet"),
    INVOLVE_OTHER_PLAYERS("Not supported yet"),
    CONSIDERING_PLAYED_CARDS("Not supported yet");

    private final String guiRepresentation;

    PlayerType(String guiRepresentation) {
        this.guiRepresentation = guiRepresentation;
    }

    /**
     * Factory for the players of a game (used for testing and loading a game). Setts a given game scenario.
     *
     * @param type  type of the player (will be generated by the Converter class)
     * @param board board of the player
     * @param idx   index of the player in the game's player array
     * @param gui   reference to the gui
     * @return a player of the given type
     */
    public static Player loadPlayerInstanceWithGivenTypeAndBoard(PlayerType type, String board,
                                                                 int idx, GUIConnector gui) {
        Player output = null;
        switch (type) {
            case HUMAN:
                output = new HumanPlayer(gui, idx, board);
                break;
            case DEFAULT:
                output = new DefaultAIPlayer(gui, idx, board);
                break;
            default:
                System.out.println("Not supported yet -> cannot instanciate desired playertype");
        }
        return output;
    }

    /**
     * Static factory for the players of a game (used for playing actual game)
     *
     * @param type       Type of the player
     * @param gui        Reference to the gui
     * @param boardSizeX X - dimension of the board
     * @param boardSizeY Y - dimension of the board
     * @return a player of the given type
     */
    public static Player getPlayerInstanceWithGivenType(PlayerType type, int idx, GUIConnector gui, int boardSizeX,
                                                        int boardSizeY) {
        Player output = null;
        switch (type) {
            case HUMAN:
                output = new HumanPlayer(gui, idx, boardSizeX, boardSizeY);
                break;
            case DEFAULT:
                output = new DefaultAIPlayer(gui, idx, boardSizeX, boardSizeY);
                break;
            default:
                System.out.println("Not supported yet -> cannot instanciate desired playertype");
        }
        return output;
    }

    /**
     * Getter for the String representation of a single element
     *
     * @return
     */
    public String getStringRepresentation() {
        return guiRepresentation;
    }

}
